hash-format = "sha256"

[[files]]
file = "config/modpack_defaults/config/NoChatReports/NCR-Client.json"

[[files]]
file = "config/modpack_defaults/config/NoChatReports/NCR-Common.json"

[[files]]
file = "config/modpack_defaults/config/NoChatReports/NCR-Encryption.json"

[[files]]
file = "config/modpack_defaults/config/ViaFabricPlus/settings.json"

[[files]]
file = "config/modpack_defaults/config/desiredservers/desiredservers.json"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"

[[files]]
file = "config/modpack_defaults/config/sodiumextras-client.toml"

[[files]]
file = "config/modpack_defaults/servers.dat"

[[files]]
file = "mods/c2me.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configmanager.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-restrictions.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/rrv.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-core-shader-support.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true
