hash-format = "sha256"

[[files]]
file = "CHANGELOG.md"
hash = "ff0f33648e7fa9165fdfb910af6461151d5c4d1997c2fdf8fdf5a0d1407af512"

[[files]]
file = "ViaFabricPlus/settings.json"
hash = "7c1361b08443d2039ddaaae206ae6c19da5e0e4cf79f1a962bb7df1febe601ac"

[[files]]
file = "config/builtinservers.json"
hash = "dcc1daf59db51ce659f4cd4d0f0239f634a2f411f1ca25cad578beb07ea180d4"

[[files]]
file = "mods/builtin-servers.pw.toml"
hash = "a58721796367f9247ad863b063d67638a6824dd0a342da690a0c1a0418e367e8"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b8270928d44781b9e59982d376bb3cc0d24089ceebef3c79d3e1e881ba7ece60"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33f865a014f3acf2c1f2c452bfe7ba1a864acad178322a6eab3759c7e63c9654"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b411b04e1dace15c7fc1465bb161c8e621750b1577282e0918f956212a57e864"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ef9c4bc27256d065df4feaba2bc05883ba22987c41cd48786070d37ae85cc8e1"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "5a6df3930d69602402cd13bf860195ac44680e2d4556e8d1254ae730fcb4b0f9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "dbbeb7a8f32fdbe0d5e44a8c7671ed2297ee8d12d4610500ac54742e70b4fb53"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "b64624f5c88721ae33b2d7acfbedf4836c76a33d6a6036ec58b629279aa9a258"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "40f1effd2c65b6c6f9a1b5dfd0903c87df02b23da6b57f389f61f361ef86d425"
metafile = true

[[files]]
file = "mods/xaeros-minimap-fair.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true
