name = "Pony Craft a New Generation Vanilla"
author = "Fauli1221"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"

[options]
no-internal-hashes = true
