name = "Pony Craft a New Generation Vanilla"
author = "Fauli1221"
version = "1.3.1-1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
no-internal-hashes = true
