name = "Pony Craft a New Generation Vanilla"
author = "Fauli1221"
version = "1.2.4-1.21.1-sodium-0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.1"
quilt = "0.26.4"

[options]
acceptable-game-versions = ["1.21"]
no-internal-hashes = true
