name = "Pony Craft a New Generation Vanilla"
author = "Fauli1221"
version = "1.2.1-1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21"
quilt = "0.26.3"

[options]
no-internal-hashes = true
